### ISSUE TITLE
REX escrow integration

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/telos-escrow#1]
## Overview
The `withdraw` function should be looked into. It just sends TLOS back to the user, but we want to send it to the escrow account. 

CPU/NET you have to wait 3 days. The reason behind the 4 days lock up is to move instantly from NET/CPU without immediately being able to withdraw. With the 10-days in the escrow contract, we don't need this fail safe anymore.

We don't want to change anything unless is strictly needed. 

## Acceptance criteria
- REX contract modified with minimal changes to send withdrawals to the escrow contract
- Initial lockup on REX reduced from 4 days to 0 days, if possible. If it can be reduced to any other number that is not zero, we should set it to 1 second. 

## Tasks
- [ ] Review escrow account
- [ ] Send withdrawal amount to escrow contract
- [ ] Test it on testnet
